name: Sync to public hub

on: [push]

jobs:
  push-directory-to-another-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Push directory to another repository directory
        uses: XenonMolecule/github-action-push-to-another-repository@0.1.0
        with:
          # Specify the directory you want to push, leave blank for root
          source-directory: ''
          # Your GitHub username or organization of the destination repository
          destination-github-username: 'trilapagg'
          # The name of the destination repository
          destination-repository-name: 'public-hub'
          # The email used for commits in the destination repository
          user-email: 'trilapagg@gmail.com'
          # The name used for commits in the destination repository
          user-name: 'trilapagg'
          # Set to the same as destination-github-username if pushing to a user's repository
          destination-repository-username: 'trilapagg'
          # Branch name in the destination repository to push changes
          target-branch: 'main'
          # Commit message for the destination repository
          commit-message: 'Update from ORIGIN_COMMIT'
          # The directory within the destination repository where files will be pushed
          target-directory: '' # Use '.' for repository root or specify a subdirectory
        env:
          # Your personal access token (PAT) with repo scope
          API_TOKEN_GITHUB: ${{ secrets.TARGET_REPO_TOKEN }}
