name: Sync to public hub

on: [push]

jobs:
  clone-and-modify-author:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure user information
        run: |
          git config --global user.email "trilapagg@gmail.com"
          git config --global user.name "trilapagg"

      - name: Replace author in commits
        run: |
          git filter-branch --env-filter '
            OLD_EMAIL="$(git log -1 --pretty=format:'%ae')"
            CORRECT_NAME="trilapagg"
            CORRECT_EMAIL="trilapagg@gmail.com"
            if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
            then
                export GIT_COMMITTER_NAME="$CORRECT_NAME"
                export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
            fi
            if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
            then
                export GIT_AUTHOR_NAME="$CORRECT_NAME"
                export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
            fi
          ' HEAD

      - name: Push changes to another repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TARGET_REPO_TOKEN }}
          repository: trilapagg/public-hub
          branch: main
